# This is a basic workflow to help you get started with Actions

name: Push Cloudflare Worker Files

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      run: |
        git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/portfolio-workers-source.git workers-src
        rsync web/api/ workers-src/
        cd workers-src
        git config user.name  "CI"
        git config user.email "cloudflare-worker-ci@github.com"
        git add .
        git commit -m "Updated workers source from code in @tmthecoder/portfolio"
        git push --force origin main
