# This is a basic workflow to help you get started with Actions

name: Push Cloudflare Worker Files

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Deploy
      run: |
        cd web/api/
        git init
        git config user.name  "CI"
        git config user.email "cloudflare-worker-ci@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/portfolio.git
        git checkout -b cloudflare-workers-source
        git add .
        git commit -m "Updated built website from code in master"
        git push --force secure-origin cloudflare-workers-source
